spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
logging:
  level:
    edu.zhoutt.mall: debug
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
mall:
  file-path-prefix: C:\software\workspace\mall\src\main\resources\static\