spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.132:3306/test2db?useUnicode=true&characterEncoding=utf-8
    username: bztuser
    password: bzt@2017
logging:
  level:
    edu.zhoutt.mall: debug
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
mall:
  ftp:
    host: 127.0.0.1
    port: 21
    username: admin
    password: admin
